### ISSUE TITLE
Can't pull while pushing

### ISSUE THREAD

**Issue by josephmturner** [RangerMauve/hyper-sdk-folder-sync-example#8]
If you pass the same `storage` location to both `pull.js` and `push.js`, you cannot `pull.js` while a `push.js` operation is running:

```
/home/joseph/.local/src/hyper-sdk-folder-sync-example/node_modules/random-access-file/index.js:246
  const err = new Error('ELOCKED: File is locked')
              ^

Error: ELOCKED: File is locked
    at createLockError (/home/joseph/.local/src/hyper-sdk-folder-sync-example/node_modules/random-access-file/index.js:246:15)
    at onopen (/home/joseph/.local/src/hyper-sdk-folder-sync-example/node_modules/random-access-file/index.js:105:19)
    at FSReqCallback.oncomplete (fs.js:180:23) {
  code: 'ELOCKED',
  path: 'test/primary-key'
}
```

Could we solve this with a unified interface which daemonizes the SDK process? Something like [this](https://github.com/silverwind/daemonize-process/blob/master/index.js)?

**Comment by RangerMauve** [comment]
I think doing tandem pull/push is outside of the scope of this repo and we should look at making a new utility to support that use case.
